exports.currencies = {
  'AED':{'label':'United Arab Emirates dirham','symbol':'د.إ'},
  'AFN':{'label':'Afghan afghani','symbol':'؋'},
  'ALL':{'label':'Albanian lek','symbol':'L'},
  'AMD':{'label':'Armenian dram','symbol':'դր'},
  'AOA':{'label':'Angolan kwanza','symbol':'Kz'},
  'ARS':{'label':'Argentine peso','symbol':'$'},
  'AUD':{'label':'Australian dollar','symbol':'$'},
  'AWG':{'label':'Aruban florin','symbol':'ƒ'},
  'AZN':{'label':'Azerbaijani manat','symbol':''},
  'BAM':{'label':'Bosnia and Herzegovina convertible mark','symbol':'KM'},
  'BBD':{'label':'Barbadian dollar','symbol':'$'},
  'BDT':{'label':'Bangladeshi taka','symbol':'৳'},
  'BGN':{'label':'Bulgarian lev','symbol':'лв'},
  'BHD':{'label':'Bahraini dinar','symbol':'.د.ب'},
  'BIF':{'label':'Burundian franc','symbol':'Fr'},
  'BMD':{'label':'Bermudian dollar','symbol':'$'},
  'BND':{'label':'Brunei dollar','symbol':'$'},
  'BOB':{'label':'Bolivian boliviano','symbol':'Bs'},
  'BRL':{'label':'Brazilian real','symbol':'R$'},
  'BSD':{'label':'Bahamian dollar','symbol':'$'},
  'BTN':{'label':'Bhutanese ngultrum','symbol':'Nu'},
  'BWP':{'label':'Botswana pula','symbol':'P'},
  'BYR':{'label':'Belarusian ruble','symbol':'Br'},
  'BZD':{'label':'Belize dollar','symbol':'$'},
  'CAD':{'label':'Canadian dollar','symbol':'$'},
  'CDF':{'label':'Congolese franc','symbol':'Fr'},
  'CHF':{'label':'Swiss franc','symbol':'Fr'},
  'CLP':{'label':'Chilean peso','symbol':'$'},
  'CNY':{'label':'Chinese yuan','symbol':'¥'},
  'COP':{'label':'Colombian peso','symbol':'$'},
  'CRC':{'label':'Costa Rican colón','symbol':'₡'},
  'CUP':{'label':'Cuban convertible peso','symbol':'$'},
  'CVE':{'label':'Cape Verdean escudo','symbol':'$'},
  'CZK':{'label':'Czech koruna','symbol':'Kč'},
  'DJF':{'label':'Djiboutian franc','symbol':'Fr'},
  'DKK':{'label':'Danish krone','symbol':'kr'},
  'DOP':{'label':'Dominican peso','symbol':'$'},
  'DZD':{'label':'Algerian dinar','symbol':'د.ج'},
  'EGP':{'label':'Egyptian pound','symbol':'ج.م'},
  'ERN':{'label':'Eritrean nakfa','symbol':'Nfk'},
  'ETB':{'label':'Ethiopian birr','symbol':'Br'},
  'EUR':{'label':'Euro','symbol':'€'},
  'FJD':{'label':'Fijian dollar','symbol':'$'},
  'FKP':{'label':'Falkland Islands pound','symbol':'£'},
  'GBP':{'label':'British pound','symbol':'£'},
  'GEL':{'label':'Georgian lari','symbol':'ლ'},
  'GHS':{'label':'Ghana cedi','symbol':'₵'},
  'GMD':{'label':'Gambian dalasi','symbol':'D'},
  'GNF':{'label':'Guinean franc','symbol':'Fr'},
  'GTQ':{'label':'Guatemalan quetzal','symbol':'Q'},
  'GYD':{'label':'Guyanese dollar','symbol':'$'},
  'HKD':{'label':'Hong Kong dollar','symbol':'$'},
  'HNL':{'label':'Honduran lempira','symbol':'L'},
  'HRK':{'label':'Croatian kuna','symbol':'kn'},
  'HTG':{'label':'Haitian gourde','symbol':'G'},
  'HUF':{'label':'Hungarian forint','symbol':'Ft'},
  'IDR':{'label':'Indonesian rupiah','symbol':'Rp'},
  'ILS':{'label':'Israeli new shekel','symbol':'₪'},
  'IMP':{'label':'Manx pound','symbol':'£'},
  'INR':{'label':'Indian rupee','symbol':''},
  'IQD':{'label':'Iraqi dinar','symbol':'ع.د'},
  'IRR':{'label':'Iranian rial','symbol':'﷼'},
  'ISK':{'label':'Icelandic króna','symbol':'kr'},
  'JEP':{'label':'Jersey pound','symbol':'£'},
  'JMD':{'label':'Jamaican dollar','symbol':'$'},
  'JOD':{'label':'Jordanian dinar','symbol':'د.ا'},
  'JPY':{'label':'Japanese yen','symbol':'¥'},
  'KES':{'label':'Kenyan shilling','symbol':'Sh'},
  'KGS':{'label':'Kyrgyzstani som','symbol':'лв'},
  'KHR':{'label':'Cambodian riel','symbol':'៛'},
  'KMF':{'label':'Comorian franc','symbol':'Fr'},
  'KPW':{'label':'North Korean won','symbol':'₩'},
  'KRW':{'label':'South Korean won','symbol':'₩'},
  'KWD':{'label':'Kuwaiti dinar','symbol':'د.ك'},
  'KYD':{'label':'Cayman Islands dollar','symbol':'$'},
  'KZT':{'label':'Kazakhstani tenge','symbol':'₸'},
  'LAK':{'label':'Lao kip','symbol':'₭'},
  'LBP':{'label':'Lebanese pound','symbol':'ل.ل'},
  'LKR':{'label':'Sri Lankan rupee','symbol':'Rs'},
  'LRD':{'label':'Liberian dollar','symbol':'$'},
  'LSL':{'label':'Lesotho loti','symbol':'L'},
  'LTL':{'label':'Lithuanian litas','symbol':'Lt'},
  'LVL':{'label':'Latvian lats','symbol':'Ls'},
  'LYD':{'label':'Libyan dinar','symbol':'ل.د'},
  'MAD':{'label':'Moroccan dirham','symbol':'د.م.'},
  'MDL':{'label':'Moldovan leu','symbol':'L'},
  'MGA':{'label':'Malagasy ariary','symbol':'Ar'},
  'MKD':{'label':'Macedonian denar','symbol':'ден'},
  'MMK':{'label':'Burmese kyat','symbol':'Ks'},
  'MNT':{'label':'Mongolian tögrög','symbol':'₮'},
  'MOP':{'label':'Macanese pataca','symbol':'P'},
  'MRO':{'label':'Mauritanian ouguiya','symbol':'UM'},
  'MUR':{'label':'Mauritian rupee','symbol':'Rs'},
  'MVR':{'label':'Maldivian rufiyaa','symbol':'.ރ'},
  'MWK':{'label':'Malawian kwacha','symbol':'MK'},
  'MXN':{'label':'Mexican peso','symbol':'$'},
  'MYR':{'label':'Malaysian ringgit','symbol':'MR'},
  'MZN':{'label':'Mozambican metical','symbol':'MT'},
  'NAD':{'label':'Namibian dollar','symbol':'$'},
  'NGN':{'label':'Nigerian naira','symbol':'₦'},
  'NIO':{'label':'Nicaraguan córdoba','symbol':'C$'},
  'NOK':{'label':'Norwegian krone','symbol':'kr'},
  'NPR':{'label':'Nepalese rupee','symbol':'Rs'},
  'NZD':{'label':'New Zealand dollar','symbol':'$'},
  'OMR':{'label':'Omani rial','symbol':'ر.ع.'},
  'PAB':{'label':'Panamanian balboa','symbol':'B/.'},
  'PEN':{'label':'Peruvian nuevo sol','symbol':'S/.'},
  'PGK':{'label':'Papua New Guinean kina','symbol':'K'},
  'PHP':{'label':'Philippine peso','symbol':'₱'},
  'PKR':{'label':'Pakistani rupee','symbol':'Rs'},
  'PLN':{'label':'Polish złoty','symbol':'zł'},
  'PRB':{'label':'Transnistrian ruble','symbol':'р.'},
  'PYG':{'label':'Paraguayan guaraní','symbol':'₲'},
  'QAR':{'label':'Qatari riyal','symbol':'ر.ق'},
  'RON':{'label':'Romanian leu','symbol':'L'},
  'RSD':{'label':'Serbian dinar','symbol':'дин'},
  'RUB':{'label':'Russian ruble','symbol':'руб.'},
  'RWF':{'label':'Rwandan franc','symbol':'Fr'},
  'SAR':{'label':'Saudi riyal','symbol':'ر.س'},
  'SBD':{'label':'Solomon Islands dollar','symbol':'$'},
  'SCR':{'label':'Seychellois rupee','symbol':'Rs'},
  'SDG':{'label':'Singapore dollar','symbol':'$'},
  'SEK':{'label':'Swedish krona','symbol':'kr'},
  'SGD':{'label':'Singapore dollar','symbol':'$'},
  'SHP':{'label':'Saint Helena pound','symbol':'£'},
  'SLL':{'label':'Sierra Leonean leone','symbol':'Le'},
  'SOS':{'label':'Somali shilling','symbol':'Sh'},
  'SRD':{'label':'Surinamese dollar','symbol':'$'},
  'SSP':{'label':'South Sudanese pound','symbol':'£'},
  'STD':{'label':'São Tomé and Príncipe dobra','symbol':'Db'},
  'SVC':{'label':'Salvadoran colón','symbol':'₡'},
  'SYP':{'label':'Syrian pound','symbol':'£'},
  'SZL':{'label':'Swazi lilangeni','symbol':'L'},
  'THB':{'label':'Thai baht','symbol':'฿'},
  'TJS':{'label':'Tajikistani somoni','symbol':'SM'},
  'TMT':{'label':'Turkmenistan manat','symbol':'m'},
  'TND':{'label':'Tunisian dinar','symbol':'د.ت'},
  'TOP':{'label':'Tongan paʻanga','symbol':'T$'},
  'TRY':{'label':'Turkish lira','symbol':'&#8378;'},
  'TTD':{'label':'Trinidad and Tobago dollar','symbol':'$'},
  'TWD':{'label':'New Taiwan dollar','symbol':'$'},
  'TZS':{'label':'Tanzanian shilling','symbol':'Sh'},
  'UAH':{'label':'Ukrainian hryvnia','symbol':'₴'},
  'UGX':{'label':'Ugandan shilling','symbol':'Sh'},
  'USD':{'label':'United States dollar','symbol':'$'},
  'UYU':{'label':'Uruguayan peso','symbol':'$'},
  'UZS':{'label':'Uzbekistani som','symbol':'лв'},
  'VEF':{'label':'Venezuelan bolívar','symbol':'Bs F'},
  'VND':{'label':'Vietnamese đồng','symbol':'₫'},
  'VUV':{'label':'Vanuatu vatu','symbol':'Vt'},
  'WST':{'label':'Samoan tālā','symbol':'T'},
  'XAF':{'label':'Central African CFA franc','symbol':'Fr'},
  'XCD':{'label':'East Caribbean dollar','symbol':'$'},
  'XOF':{'label':'West African CFA franc','symbol':'Fr'},
  'XPF':{'label':'CFP franc','symbol':'Fr'},
  'YER':{'label':'Yemeni rial','symbol':'﷼'},
  'ZAR':{'label':'South African rand','symbol':'R'},
  'ZMW':{'label':'Zambian kwacha','symbol':'ZK'},
  'ZWL':{'label':'Zimbabwean dollar','symbol':'$'}
};
